targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - "**/entities/**.dart"
        options:
          any_map: true
          explicit_to_json: true
      source_gen:combining_builder:
        options:
          preamble: |
            // coverage:ignore-file
